/// Content for the in-app Privacy Policy / Terms of Service screens.
///
/// Kept in sync by hand with frontend/docs/PRIVACY_POLICY.md and
/// TERMS_OF_SERVICE.md - those markdown files are the canonical, fuller
/// version (meant for GitHub/web hosting); this is the same content
/// reflowed for an in-app scroll view. Update both when the policy changes.
class LegalSection {
  const LegalSection(this.heading, this.body);
  final String heading;
  final String body;
}

class LegalDocument {
  const LegalDocument({required this.title, required this.lastUpdated, required this.intro, required this.sections});
  final String title;
  final String lastUpdated;
  final String intro;
  final List<LegalSection> sections;
}

const privacyPolicyDocument = LegalDocument(
  title: 'Privacy Policy',
  lastUpdated: '2026-08-14',
  intro:
      'Status: draft, not yet reviewed by a lawyer. Velar is not currently '
      'published on any app store. This describes what the app and its '
      'backend actually do - it has not received formal legal review.',
  sections: [
    LegalSection(
      'Who this is',
      'Velar is developed by an individual developer, not a registered '
          'company.\n\nDeveloper: Lokesh Ram Chand\nContact: lokeshramchand@gmail\n\n'
          'Contact that address with questions about this policy or your data.',
    ),
    LegalSection(
      'What Velar is',
      'A personal finance app. You upload a Google Pay statement PDF you '
          'export yourself, and Velar parses it into a spending overview, '
          'category breakdowns, recurring-payment detection, and a '
          'searchable transaction history. Velar is not a bank or payment '
          'processor and cannot move money - it only reads statements you '
          'choose to give it.',
    ),
    LegalSection(
      'What data we collect',
      'Account: email, and a password hashed with Argon2id before it '
          'touches the database (never stored or logged in plain text), '
          'plus an optional display name.\n\n'
          'Statement data: the PDF you upload, and every parsed '
          'transaction - merchant, amount, category, timestamp, type, '
          'status, UPI reference number, paying bank, and the last 4 '
          'digits of the account number (never the full number).\n\n'
          'What you actively provide: category corrections ("Wrong '
          'category"), used to improve future categorization.\n\n'
          'What we do not collect: location, contacts, camera, microphone, '
          'advertising identifiers. No analytics or crash-reporting SDK is '
          'integrated into this app.',
    ),
    LegalSection(
      'How your data is processed',
      'The database (MongoDB) and vector search index (Milvus) are '
          'self-hosted, not a third-party managed service. Categorization '
          'and "why this category" explanations are generated by a '
          'locally-run language model (Ollama) - your data is not sent to '
          'OpenAI, Anthropic, Google, or any other external AI provider.',
    ),
    LegalSection(
      'How your data is used',
      'To show you the app\'s screens, to improve categorization accuracy '
          'from corrections you submit, and to generate optional local '
          'notifications shown entirely on your device. Your data is '
          'never sold and is not shared with third parties for their own '
          'marketing or analytics - there is no code path in this app that '
          'does that.',
    ),
    LegalSection(
      'Data retention and deletion',
      'Delete any single statement any time from Profile → Manage '
          'periods - this permanently removes that statement\'s PDF, '
          'transactions, and processing history, and cannot be undone. '
          'Full account deletion isn\'t self-service yet - email the '
          'contact address above to request it. Signing out only clears '
          'your session on that device; it does not delete server-side '
          'data.',
    ),
    LegalSection(
      'Security',
      'Argon2id password hashing. Short-lived JWT access tokens (15 '
          'minutes) with a rotating, single-use refresh token revoked on '
          'reuse. Backend traffic is required to be HTTPS outside local '
          'development. On-device session tokens use platform secure '
          'storage (Android encrypted preferences / iOS Keychain).\n\n'
          'No system is perfectly secure, and infrastructure run by an '
          'individual developer doesn\'t carry the guarantees of a large '
          'regulated institution - use your judgment about what you '
          'upload.',
    ),
    LegalSection(
      'Your rights',
      'You can always: see exactly what\'s stored (nothing is hidden in '
          'the app), delete any statement yourself immediately, request '
          'full account deletion by email, and export your transactions '
          'as CSV from Profile → Export my data.',
    ),
    LegalSection(
      'Children\'s privacy',
      'Velar is not directed at children and is not knowingly used to '
          'collect data from anyone under 13. Contact us if you believe a '
          'child has created an account.',
    ),
    LegalSection(
      'Changes to this policy',
      'Material changes update the date above and, where practical, are '
          'announced in-app.',
    ),
  ],
);

const termsOfServiceDocument = LegalDocument(
  title: 'Terms of Service',
  lastUpdated: '2026-08-14',
  intro:
      'Status: draft, not yet reviewed by a lawyer. Velar is not currently '
      'published on any app store. Read alongside the Privacy Policy, '
      'which covers your data specifically.',
  sections: [
    LegalSection(
      'Who this is',
      'Developer: Lokesh Ram Chand\nContact: lokeshramchand@gmail',
    ),
    LegalSection(
      'What Velar is (and isn\'t)',
      'Velar reads Google Pay statement PDFs you upload into a spending '
          'overview, categorization, recurring-payment detection, and '
          'transaction history.\n\nVelar is not: a bank, payment processor, '
          'or financial institution; able to move money or access your '
          'bank/UPI account directly; or a source of financial, tax, or '
          'investment advice. Categorization and signals are automated '
          'best-effort output - verify anything that matters against your '
          'actual records before acting on it.',
    ),
    LegalSection(
      'Your account',
      'You must provide a valid email and password, and are responsible '
          'for keeping them confidential and for activity under your '
          'account. You must be legally capable of agreeing to these '
          'terms in your jurisdiction. Don\'t share your account with '
          'people you don\'t trust with your financial data.',
    ),
    LegalSection(
      'Acceptable use',
      'Don\'t: upload statements you\'re not authorized to view, attempt '
          'to access another user\'s account or data, interfere with or '
          'reverse-engineer the backend beyond normal app usage, or use '
          'the service unlawfully. Accounts violating these terms may be '
          'suspended or terminated.',
    ),
    LegalSection(
      'Accuracy of statement processing',
      'Parsing and categorization are automated and can be wrong - '
          'misread amounts, mis-parsed dates, misclassified merchants, or '
          'missed transactions are possible. "Why this category" '
          'explanations describe the automated reasoning, not a guarantee '
          'of accuracy. Cross-check anything you rely on financially '
          'against your actual Google Pay / bank records.',
    ),
    LegalSection(
      'Your content',
      'You retain ownership of the statements you upload and data '
          'derived from them. Uploading grants Velar the permissions '
          'needed to store, parse, and process it to provide the app\'s '
          'features, as described in the Privacy Policy. We don\'t use '
          'your data beyond providing the app and improving '
          'categorization accuracy.',
    ),
    LegalSection(
      'Service availability',
      'Velar runs on infrastructure operated by an individual developer, '
          'not a redundant commercial hosting setup. The service may be '
          'unavailable, slow, or interrupted without notice, with no '
          'uptime guarantee. Don\'t rely on Velar as your sole financial '
          'record - your bank and Google Pay remain authoritative.',
    ),
    LegalSection(
      'Disclaimer and liability',
      'Velar is provided "as is," without warranties of any kind, '
          'including fitness for a particular purpose, accuracy, or '
          'non-infringement. To the maximum extent permitted by law, the '
          'developer is not liable for indirect, incidental, or '
          'consequential damages arising from your use of the app, '
          'including decisions made based on its output.',
    ),
    LegalSection(
      'Termination',
      'Stop using Velar any time by signing out and requesting account '
          'deletion. We may suspend or terminate access for violations of '
          'Acceptable use.',
    ),
    LegalSection(
      'Changes to these terms',
      'Material changes update the date above and, where practical, are '
          'announced in-app. Continued use after a change means you '
          'accept the update.',
    ),
    LegalSection(
      'Governing law',
      'Placeholder pending formal legal review before any public '
          'release: [GOVERNING LAW / JURISDICTION TBD].',
    ),
  ],
);
